name: Publish to GitHub Packages
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16.18.0
          cache: yarn
          registry-url: https://npm.pkg.github.com/
          scope: '@portablestudios'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build the project
        run: yarn build

      - name: Publish the project
        run: yarn publish --non-interactive
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
